export const ALL_CARD_SUCCESS = "ALL_CARD_SUCCESS";

export const CERTAIN_CARD_SUCCESS = "CERTAIN_CARD_SUCCESS";

export const ALL_SELLER_SUCCESS = "ALL_SELLER_SUCCESS";

export const USER_TOKENS_SUCCESS= "USER_REQUEST_FAILURE";





