export const ALL_REQUEST_FAILURE = "ALL_REQUEST_FAILURE";
export const ALL_REQUEST_STARTED = "ALL_REQUEST_STARTED";


export const ALL_CARD_SUCCESS = "ALL_CARD_SUCCESS";

export const CERTAIN_CARD_SUCCESS = "CERTAIN_CARD_SUCCESS";

export const ALL_AUTHOR_SUCCESS = "ALL_AUTHOR_SUCCESS";
export const ALL_LOCATION_SUCCESS = "ALL_LOCATION_SUCCESS";
