export const ALL_REQUEST_FAILURE = "ALL_REQUEST_FAILURE";
export const ALL_REQUEST_STARTED = "ALL_REQUEST_STARTED";


export const ALL_CARD_SUCCESS = "ALL_CARD_SUCCESS";

export const CERTAIN_CARD_SUCCESS = "CERTAIN_CARD_SUCCESS";

export const ALL_SELLER_SUCCESS = "ALL_SELLER_SUCCESS";

export const USER_REQUEST_FAILURE = "USER_REQUEST_FAILURE";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_STARTED = "USER_REQUEST_STARTED";

export const USER_REGISTER_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_TOKENS_SUCCESS = "USER_TOKENS_SUCCESS";



